### ISSUE TITLE
ERROR:tbk.soap.requestor.SoapRequestor:SOAP request method `initTransaction` failed with unexpected exception

### ISSUE THREAD

**Issue by eundev** [cornershop/python-tbk#24]
Hello, 

I am calling the webpay_service.init_transaction() function with the following inputs:

amount = 14990
buy_order= "some_uid"
session_id = "some_session_id"

**This is the code**
        transaction = webpay_service.init_transaction(
            amount=int(request.data["amount"]),
            buy_order=request.data["buy_order"],
            return_url=BASE_URL + "/normal/return",
            final_url=BASE_URL + "/normal/final",
            session_id=request.data["session_id"],
        )
        print(transaction)
        print("RIGHT AFTER TRANSACTION BEFORE REPONSE")
        return Response({}, status=status.HTTP_200_OK)

I would love it if you could help me with this issue, thank you in advance.

**This is the full traceback:**
ERROR:tbk.soap.requestor.SoapRequestor:SOAP request method `initTransaction` failed with unexpected exception
Traceback (most recent call last):
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/tbk/soap/requestor.py", line 72, in request
    request, timeout=timeout
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/tbk/soap/zeep_client.py", line 59, in request
    result = method(*request.args, **request.kwargs)
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 185, in process_reply
    client.wsse.verify(doc)
  File "/Users/eunleedev/Desktop/Client-Work/Global-Retail-Group/Code/env/lib/python3.7/site-packages/tbk/soap/zeep_client.py", line 103, in verify
    raise InvalidSignatureResponse(envelope)
tbk.soap.exceptions.InvalidSignatureResponse: <Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x11234df88>
<Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x11234df88>
Bad Request: /payments/initiate-transaction/
WARNING:django.request:Bad Request: /payments/initiate-transaction/

**Comment by eundev** [comment]
I found that the exact line where the error arises is in soap/wsse.py/verify_envelope (line 146-ish, where it calls ctx.verify(signature)

In the code below, I've commented out the ctx.verify(signature) to confirm that the error is in that line.

`def verify_envelope(envelope, key):
    """Verify WS-Security signature on given SOAP envelope with given cert.

    Expects a document like that found in the sample XML in the ``sign()``
    docstring.

    Raise SignatureValidationFailed on failure, silent on success.

    """

    signature = get_signature_node(envelope)
    if signature is not None:
        ctx = get_signature_context(signature, envelope)
        ctx.key = key
        try:
            print("COMMENTED VERIFICATION OUT")
            # ctx.verify(signature)
            return True
        except xmlsec.Error as e:
            # Sadly xmlsec gives us no details about the reason for the failure, so
            # we have nothing to pass on except that verification failed.
            return False
    return False`

**Comment by elramirezv123** [comment]
@eundev I have the same error, could you solve it?

**Comment by eundev** [comment]
Hola Alejandro,

Perdon por la respuesta tarde. Lo logré arreglar y es un problema de las
credenciales. Algo así de que la credencial que usaba el proyecto no era la
que se tenía que usar.
Si gustas mañana (hoy, la verdad) tipo 3PM-5PM te puedo mandar las
credenciales de integración que usé.

Saludos

**Comment by gonzalomc** [comment]
Hola @eundev , yo tengo el mismo problema. Me podrías compartir las credenciales que utilizaste para integración. Muchas gracias. Saludos.

**Comment by MatiasMingo** [comment]
Tengo el mismo error.
Específicamente no entiendo muy bien cual es el formato que deben tener buy_order y session_id en:
transaction = webpay_service.init_transaction(
amount=int(request.data["amount"]),
buy_order=request.data["buy_order"],
return_url=BASE_URL + "/normal/return",
final_url=BASE_URL + "/normal/final",
session_id=request.data["session_id"],
)
Podrían dar un ejemplo.

Saludos y gracias de antemano.

**Comment by elramirezv123** [comment]
@MatiasMingo El error era por **las credenciales** que se deben utilizar dependiendo del ambiente. [En este repo](https://github.com/TransbankDevelopers/transbank-webpay-credenciales/tree/master/integracion) están las del ambiente de integración.

Por otro lado, `buy_order` y `session_id` son strings. Estas variables pueden ser strings vacíos si es que así lo deseas (no lo recomiendo). `buy_order`es para hacer referencia a la orden de compra **dentro del contexto de tu aplicación** y la `session_id` es útil hacer referencia al usuario, esta se utiliza normalmente cuando webpay te "devuelve" finalmente a tu aplicación.

**Comment by MatiasMingo** [comment]
@elramirezv123 Muchísimas gracias!!

**Comment by paulpopaul** [comment]
Estimados tengo el mismo error

InvalidSignatureResponse at /integracion_tbk/normal_init_transaction
<Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x7f292f37ca40>



Exception Value: | <Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x7f292f37ca40>

/home/lamascada2/webapps/lamascadaweb/lamascadawebenv/lib/python3.8/site-packages/tbk/soap/zeep_client.py in verify, line 103


envelope | <Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x7f292f37ca40>
self | <tbk.soap.zeep_client.ZeepWsseSignature object at 0x7f292fee14f0>


Ojala, alguien pueda ayudar

**Comment by elramirezv123** [comment]
@paulpopaul Probaste con las credenciales del ambiente de integración ?

**Comment by paulpopaul** [comment]
@elramirezv123 
Hola .sí, ambiente de integración funciona perfecto.

estoy pasando a ambiente de producción. listo el crt con el código de comercio, 
y dado visto bueno por parte de tbk. certificado generado bajo el algoritmo sha256RSA.

ahora seguí los pasos que comenta @eundev en su segunda respuesta.
comentando la linea de código # ctx.verify(signature)
y funciona perfecto, mi pregunta es eso es seguro ?

por lo menos funciona, pero el error se produce porque mi certificado no es válido¿?

**Comment by elramirezv123** [comment]
Claro, pero puede ser por el tuyo o porque no estás ocupando el correcto de Transbank. En mi caso fue porque no estaba ocupando el correcto de Transbank. Estas ocupando [este](https://github.com/TransbankDevelopers/transbank-webpay-credenciales/tree/master/produccion) para producción?

**Comment by elramirezv123** [comment]
@paulpopaul También, alguien de Transbank hizo esta pequeña [app web](https://certificados.digitalpartner.cl) para poder generar los certificados, quizás podrías ocuparla para asegurarte 😄

**Comment by paulpopaul** [comment]
@elramirezv123, Estimado, agradecido por su tiempo y respuestas.

no sabía de ese certificado de transbank, dónde debería ir?

sólo agregue el nuevo CRT generado con mi código de comercio, con sus respectivas carpetas. luego sustituí el código CRT de ambiente de integración por el nuevo. pensé que era llegar y remplazar los códigos. aparte de cambiar ambiente DEVELOPMENT A PRODUCTION.

ahora me comenta de ese certificado-publico-transbank.crt, pero no tengo idea dónde debería ir.

**Comment by elramirezv123** [comment]
@paulpopaul Cuando inicializa tbk.commerce.Commerce, debe ser con 2 certificados y una llave de esta forma:

```python
tbk.commerce.Commerce(
    commerce_code=COMMERCE_CODE,
    key_data="key_data", # Este debe ser tu llave pública
    cert_data="cert_data", # Este debe ser el certificado que generaste
    tbk_cert_data="tbk_cert_data" # Este tiene que ser el certificado público de producción de Transbank,
    environment=PRODUCTION
)
```

**Comment by paulpopaul** [comment]
@elramirezv123 eso era, no estaba ocupando el CRT correcto de Transbank. Muy agradecido !
